from __future__ import annotations

# ====================================================================================================
# MARK: OVERVIEW
# ====================================================================================================
# Workspace menu helpers for KoreCode/app.
# Provides the focused helpers and module-level behaviour grouped into this file.
# ====================================================================================================

import ast
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


MENU_FILENAME          = "KoreCodeWorkspace.md"
_SKIP_DIRS             = {
    ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".venv",
    "__pycache__", "node_modules",
}
_MAX_FILE_BYTES        = 1_500_000
_MAX_SIGNATURE_LENGTH  = 220


@dataclass(slots=True)
class SignatureEntry:
    line:      int
    kind:      str
    name:      str
    signature: str


def menu_path_for(root: Path) -> Path:
    return root / MENU_FILENAME


def build_workspace_menu(root: Path) -> dict:
    root        = root.resolve()
    menu_path   = menu_path_for(root)
    directories = []
    files       = []
    lines       = [
        "# KoreCode Workspace Menu",
        "",
        f"Root: `{root}`",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "This file is generated by KoreCode to provide a menu of workspace files",
        "and Python call signatures that may be imported or reused elsewhere.",
        "",
        "## Directory Tree",
        "",
    ]

    for current in _iter_directories(root):
        rel_dir = _rel_path(current, root)
        directories.append(rel_dir)
        depth   = 0 if rel_dir == "." else rel_dir.count("/")
        label   = root.name if rel_dir == "." else current.name
        indent  = "  " * depth
        lines.append(f"{indent}- {label}/")

    lines.extend([
        "",
        "## File Inventory",
        "",
    ])

    for file_path in _iter_files(root, menu_path):
        rel_file    = _rel_path(file_path, root)
        signatures  = _python_signatures(file_path)
        if not signatures:
            continue
        files.append(
            {
                "path":       rel_file,
                "signatures": [
                    {
                        "line":      entry.line,
                        "kind":      entry.kind,
                        "name":      entry.name,
                        "signature": entry.signature,
                    }
                    for entry in signatures
                ],
            }
        )
        lines.append(f"### `{rel_file}`")
        for entry in signatures:
            lines.append(f"- L{entry.line} {entry.kind}: `{entry.signature}`")
        lines.append("")

    content = "\n".join(lines).rstrip() + "\n"
    menu_path.write_text(content, encoding="utf-8")
    return {
        "ok":               True,
        "root":             str(root),
        "menu_path":        str(menu_path),
        "menu_file_name":   MENU_FILENAME,
        "directory_count":  len(directories),
        "file_count":       len(files),
        "content_hash_len": len(content),
        "content":          content,
        "files":            files,
    }


def read_workspace_menu(root: Path) -> dict | None:
    path = menu_path_for(root.resolve())
    if not path.exists() or not path.is_file():
        return None
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return None
    return {
        "root":           str(root.resolve()),
        "menu_path":      str(path),
        "menu_file_name": MENU_FILENAME,
        "content":        content,
    }


def _iter_directories(root: Path):
    yield root
    for path in sorted(root.rglob("*")):
        if not path.is_dir():
            continue
        if _should_skip(path, root):
            continue
        yield path


def _iter_files(root: Path, menu_path: Path):
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path == menu_path:
            continue
        if _should_skip(path, root):
            continue
        if path.suffix.lower() not in {".py", ".pyi"}:
            continue
        try:
            if path.stat().st_size > _MAX_FILE_BYTES:
                continue
        except OSError:
            continue
        yield path


def _should_skip(path: Path, root: Path) -> bool:
    try:
        rel_parts = path.relative_to(root).parts
    except ValueError:
        return True
    return any(part in _SKIP_DIRS for part in rel_parts)


def _rel_path(path: Path, root: Path) -> str:
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError:
        return str(path)
    return rel or "."


def _python_signatures(path: Path) -> list[SignatureEntry]:
    try:
        source = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        source = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []

    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    entries: list[SignatureEntry] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            entries.append(
                SignatureEntry(
                    line      = int(getattr(node, "lineno", 1)),
                    kind      = "function",
                    name      = node.name,
                    signature = _clip_signature(_format_function_signature(node)),
                )
            )
        elif isinstance(node, ast.AsyncFunctionDef):
            entries.append(
                SignatureEntry(
                    line      = int(getattr(node, "lineno", 1)),
                    kind      = "async function",
                    name      = node.name,
                    signature = _clip_signature(_format_function_signature(node, is_async=True)),
                )
            )
        elif isinstance(node, ast.ClassDef):
            entries.append(
                SignatureEntry(
                    line      = int(getattr(node, "lineno", 1)),
                    kind      = "class",
                    name      = node.name,
                    signature = _clip_signature(_format_class_signature(node)),
                )
            )
            entries.extend(_class_method_signatures(node))
    return entries


def _class_method_signatures(node: ast.ClassDef) -> list[SignatureEntry]:
    out: list[SignatureEntry] = []
    for child in node.body:
        if isinstance(child, ast.FunctionDef):
            out.append(
                SignatureEntry(
                    line      = int(getattr(child, "lineno", 1)),
                    kind      = "method",
                    name      = f"{node.name}.{child.name}",
                    signature = _clip_signature(_format_method_signature(node.name, child)),
                )
            )
        elif isinstance(child, ast.AsyncFunctionDef):
            out.append(
                SignatureEntry(
                    line      = int(getattr(child, "lineno", 1)),
                    kind      = "async method",
                    name      = f"{node.name}.{child.name}",
                    signature = _clip_signature(_format_method_signature(node.name, child, is_async=True)),
                )
            )
    return out


def _format_class_signature(node: ast.ClassDef) -> str:
    if not node.bases:
        return f"class {node.name}"
    bases = ", ".join(_safe_unparse(base) for base in node.bases)
    return f"class {node.name}({bases})"


def _format_function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef, is_async: bool = False) -> str:
    args          = []
    positional    = list(node.args.posonlyargs) + list(node.args.args)
    defaults      = list(node.args.defaults)
    default_start = len(positional) - len(defaults)

    for index, arg in enumerate(positional):
        formatted = _format_arg(arg)
        if index >= default_start and defaults:
            formatted = f"{formatted}={_safe_unparse(defaults[index - default_start])}"
        args.append(formatted)

    if node.args.vararg:
        args.append(f"*{_format_arg(node.args.vararg)}")
    elif node.args.kwonlyargs:
        args.append("*")

    for kwarg, default in zip(node.args.kwonlyargs, node.args.kw_defaults):
        formatted = _format_arg(kwarg)
        if default is not None:
            formatted = f"{formatted}={_safe_unparse(default)}"
        args.append(formatted)

    if node.args.kwarg:
        args.append(f"**{_format_arg(node.args.kwarg)}")

    prefix   = "async def " if is_async else "def "
    returns  = f" -> {_safe_unparse(node.returns)}" if node.returns is not None else ""
    return f"{prefix}{node.name}({', '.join(args)}){returns}"


def _format_method_signature(class_name: str, node: ast.FunctionDef | ast.AsyncFunctionDef, is_async: bool = False) -> str:
    signature = _format_function_signature(node, is_async=is_async)
    prefix    = "async def " if is_async else "def "
    if signature.startswith(prefix):
        signature = signature[len(prefix):]
    return f"{class_name}.{signature}"


def _format_arg(arg: ast.arg) -> str:
    if arg.annotation is None:
        return arg.arg
    return f"{arg.arg}: {_safe_unparse(arg.annotation)}"


def _safe_unparse(node: ast.AST | None) -> str:
    if node is None:
        return ""
    try:
        return ast.unparse(node)
    except Exception:
        return "..."


def _clip_signature(signature: str) -> str:
    text = " ".join(str(signature).split())
    if len(text) <= _MAX_SIGNATURE_LENGTH:
        return text
    return text[:_MAX_SIGNATURE_LENGTH - 3].rstrip() + "..."
